version: '3.9'
services:
  app:
    build: .
    container_name: edusync_app
    ports:
      - "${SERVER_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - uploads_data:/app/uploads
    networks:
      - edusync_network

  db:
    image: postgres:17-alpine
    container_name: edusync_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5431:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations/pgadmin-init:/docker-entrypoint-initdb.d
    networks:
      - edusync_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: edusync_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - edusync_network
  
volumes:
  db_data:
  uploads_data:
  pgadmin_data:

networks:
  edusync_network:
    driver: bridge